drt-multitask: better error handling

diff --git a/drt-multitask b/drt-multitask
--- a/drt-multitask
+++ b/drt-multitask
@@ -1,14 +1,30 @@
-#! /bin/sh
+#! /usr/bin/env bash
+
+set -u
+set -e
+set -o pipefail
+
+_error () {
+	local format="${1}"; shift
+
+	printf "ERROR: ${format}\n" "${@}" >&2
+	return 1
+}
 
 if command -v parallel >/dev/null
 then
-	parallel --will-cite --bar "${@}"
+	if ! parallel --will-cite --bar --halt now,fail=1 "${@}"
+	then
+		_error 'failed to execute tasks'
+	fi
 elif command -v xargs >/dev/null
 then
-	xargs "${@}"
+	if ! xargs "${@}"
+	then
+		_error 'failed to execute tasks'
+	fi
 else
-	printf 'ERROR: your system must provide parallel or xargs\n' >&2
-	exit 1
+	_error 'your system must provide parallel or xargs'
 fi
 
 #EOF
